/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '585933' at '8/28/18 7:26 AM' with Gradle 2.14
 *
 * @author 585933, @date 8/28/18 7:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
